### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rthakker549**

### CODE REVIEW

**Comment by hwaldstein1997** [comment]
Why was this merged into master? Typically, one waits to merge something into the master branch until it's tested and considered "production ready". I haven't looked at the code, but my guess would be that isn't the case yet for this code.

**Comment by rthakker549** [comment]
Melanie Wanted to Merge it into Master

**Comment by hwaldstein1997** [comment]
Interesting. I guess she can if she wants, although it seems somewhat unorthodox. My biggest issue would be that the associated back-end code is broken. But, it's done now.

**Comment by mpowell14** [comment]
Sorry Harley, there was something weird happening with the master branch giving us a 404 error. I wasn't thinking and we could have just merged into dev and not into master. My bad.

**Comment by hwaldstein1997** [comment]
You're cool. I was just like "Why... ?". Don't worry about it.

**Pull request merged**
